### ISSUE TITLE
@meigenコマンド

### ISSUE THREAD

**Issue by otiai10** [otiai10/chant#70]

**Comment by otiai10** [comment]
@kazz187 具体的にどういう機能のイメージですか？

**Comment by kazz187** [comment]
Chant 風表記法だと

```
{@meigen: speaker_name, context}
```

みたいに表現すると

```
  context
           - speaker_name -
```

みたいなおしゃれな装飾(よくある名言の装飾枠)に変換したい

2015-02-09 16:19 GMT+09:00 OCHIAI Hiromu <notifications@github.com>:

**Comment by otiai10** [comment]
ふむ。quoteのオシャレ版だと思えばいいですかね

**Comment by kazz187** [comment]
Chant 風表記法だと

```
{@meigen: speaker_name, context}
```

みたいに表現すると

```
  context
           - speaker_name -
```

みたいなおしゃれな装飾(よくある名言の装飾枠)に変換したい

**Comment by kazz187** [comment]
font を明朝体にするとか、大きくするとか

**Comment by otiai10** [comment]
@kazz187 イメージです
![2015-02-09 16 48 44](https://cloud.githubusercontent.com/assets/931554/6102532/8d178500-b07b-11e4-8c93-c9b30138c70f.png)

**Comment by otiai10** [comment]
```css
element.style {
  font-size: 4em;
  font-style: italic;
  font-family: serif;
  margin-left: 20px;
  text-shadow: 1px 1px 1px #bbb;
}
```
